import {
  Home,
  User,
  Code,
  Briefcase,
  Mail,
  Github,
  MessageCircle,
  Send as TelegramIcon,
  Blocks,
  Database,
  Smartphone,
  Globe,
  Brain,
  Shield,
  Cloud,
  Palette,
  Award,
  Users,
  TrendingUp,
  CheckCircle,
  Calendar,
  MapPin,
  GraduationCap,
  Phone,
  Send,
  MessageSquare,
  FileSearch,
  TestTube,
  Rocket,
  Atom,
  FileText,
  Terminal,
  Box,
  Cpu,
  Braces,
  Binary,
  Component,
  Server,
  GitBranch,
  Zap,
  Settings,
  Layers,
  MonitorSpeaker,
  Smartphone as Mobile,
  Code2,
  BarChart3,
  Lock,
  Shield as Security,
  Wrench,
} from "lucide-react";

import type {
  Project,
  Experience,
  Education,
  SkillCategory,
  SocialLink,
  Achievement,
  NavItem,
  WorkflowStep,
} from "@/types";

// Navigation items
export const NAV_ITEMS: NavItem[] = [
  { href: "/", label: "Home", icon: Home },
  { href: "/about", label: "About", icon: User },
  { href: "/skills", label: "Skills", icon: Code },
  { href: "/projects", label: "Projects", icon: Briefcase },
  { href: "/contact", label: "Contact", icon: Mail },
];

// Social media links
export const SOCIAL_LINKS: SocialLink[] = [
  {
    href: "https://github.com/Enthusiastic001122",
    icon: Github,
    label: "GitHub",
  },
  {
    href: "https://discord.gg/yW4aYSdR",
    icon: MessageCircle,
    label: "Discord",
  },
  {
    href: "https://t.me/GreenOsmi",
    icon: TelegramIcon,
    label: "Telegram",
  },
];

// Professional contact information - Removed as per user request
// Users can contact via social links: GitHub, Discord, Telegram

// Core technical skills
export const CORE_SKILLS = [
  "React & Next.js",
  "Node.js & Express",
  "Solidity & Web3",
  "TypeScript",
  "PostgreSQL & MongoDB",
  "AWS & Docker",
];

// Technology icon mapping
export const TECHNOLOGY_ICONS: Record<string, any> = {
  // Frontend
  React: Atom,
  "Next.js": Zap,
  "Vue.js": Component,
  TypeScript: FileText,
  JavaScript: Braces,
  HTML5: Code,
  CSS3: Palette,
  Tailwind: Palette,
  SASS: Palette,
  Webpack: Settings,

  // Backend
  "Node.js": Server,
  Express: Server,
  Python: Terminal,
  Django: Database,
  FastAPI: Zap,
  PostgreSQL: Database,
  MongoDB: Database,
  MySQL: Database,
  Redis: Database,
  GraphQL: Globe,
  REST: Globe,

  // Blockchain
  Solidity: Binary,
  "Web3.js": Globe,
  "Ethers.js": Globe,
  Hardhat: Wrench,
  Truffle: Wrench,
  IPFS: Cloud,
  MetaMask: Lock,
  OpenZeppelin: Security,

  // Cloud & DevOps
  AWS: Cloud,
  "Google Cloud": Cloud,
  Docker: Box,
  Kubernetes: Component,
  Terraform: Settings,
  Jenkins: Settings,
  "GitHub Actions": GitBranch,
  CircleCI: Settings,

  // Mobile
  "React Native": Mobile,
  Flutter: Component,
  Expo: Mobile,
  Swift: Cpu,
  Kotlin: Cpu,
  Firebase: Cloud,
  "App Store": Smartphone,

  // Design & Tools
  Figma: Component,
  "Adobe XD": Palette,
  Git: GitBranch,
  GitHub: Github,
  "VS Code": Code,
  Postman: Globe,
  Jira: BarChart3,
  Slack: MessageCircle,
};

// Key professional achievements
export const ACHIEVEMENTS: Achievement[] = [
  {
    icon: Award,
    label: "Certified Blockchain Developer",
    color: "text-yellow-400",
  },
  { icon: Users, label: "Led 10+ Development Teams", color: "text-blue-400" },
  {
    icon: TrendingUp,
    label: "$50M+ in DeFi TVL Managed",
    color: "text-green-400",
  },
  {
    icon: CheckCircle,
    label: "100+ Smart Contracts Deployed",
    color: "text-purple-400",
  },
];

// Professional experience
export const EXPERIENCES: Experience[] = [
  {
    title: "Lead Blockchain Architect",
    company: "TechCorp Inc.",
    period: "2023 - Present",
    description:
      "Architecting enterprise blockchain solutions and leading a team of 15+ developers. Delivered $50M+ TVL DeFi platform and reduced smart contract gas costs by 40%.",
    achievements: [
      "Led $50M TVL DeFi platform",
      "40% gas optimization",
      "Team of 15+ developers",
    ],
  },
  {
    title: "Senior Full-Stack Developer",
    company: "FinanceFlow Solutions",
    period: "2021 - 2023",
    description:
      "Developed high-frequency trading systems and real-time analytics platforms. Built microservices handling 10M+ requests/day with 99.99% uptime.",
    achievements: ["10M+ daily requests", "99.99% uptime", "HFT systems"],
  },
  {
    title: "Blockchain Developer",
    company: "CryptoInnovate",
    period: "2020 - 2021",
    description:
      "Specialized in DeFi protocol development and smart contract security. Deployed 100+ audited smart contracts with zero security incidents.",
    achievements: [
      "100+ smart contracts",
      "Zero security incidents",
      "DeFi protocols",
    ],
  },
  {
    title: "Full-Stack Developer",
    company: "CloudTech Solutions",
    period: "2018 - 2020",
    description:
      "Built scalable web applications and cloud infrastructure. Migrated legacy systems to modern architectures, improving performance by 300%.",
    achievements: [
      "300% performance improvement",
      "Cloud migration",
      "Modern architecture",
    ],
  },
];

// Educational background
export const EDUCATION: Education[] = [
  {
    degree: "Master of Computer Science",
    school: "University of Toronto",
    year: "2018",
    specialization: "Distributed Systems & Cryptography",
    gpa: "3.9/4.0",
  },
  {
    degree: "Bachelor of Software Engineering",
    school: "University of Waterloo",
    year: "2016",
    specialization: "Software Architecture & Algorithms",
    gpa: "3.8/4.0",
  },
];

// Professional certifications
export const CERTIFICATIONS = [
  "AWS Certified Solutions Architect - Professional",
  "Certified Ethereum Developer (ConsenSys)",
  "Google Cloud Professional Cloud Architect",
  "Kubernetes Certified Application Developer",
  "MongoDB Certified Developer Associate",
  "Certified Blockchain Security Professional",
  "Docker Certified Associate",
  "Terraform Associate Certification",
];

// Technical skill categories
export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    title: "Frontend Development",
    icon: Code,
    color: "#3b82f6",
    skills: [
      { name: "React/Next.js", level: 95, icon: Atom },
      { name: "TypeScript", level: 92, icon: FileText },
      { name: "JavaScript ES6+", level: 94, icon: Braces },
      { name: "Modern CSS", level: 88, icon: Palette },
    ],
    technologies: [
      "React",
      "Next.js",
      "Vue.js",
      "TypeScript",
      "JavaScript",
      "HTML5",
      "CSS3",
      "Tailwind",
      "SASS",
      "Webpack",
    ],
  },
  {
    title: "Backend Development",
    icon: Database,
    color: "#10b981",
    skills: [
      { name: "Node.js/Express", level: 94, icon: Server },
      { name: "Python/FastAPI", level: 90, icon: Terminal },
      { name: "Database Design", level: 88, icon: Database },
      { name: "API Architecture", level: 92, icon: Globe },
    ],
    technologies: [
      "Node.js",
      "Express",
      "Python",
      "Django",
      "FastAPI",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "GraphQL",
      "REST APIs",
    ],
  },
  {
    title: "Blockchain Development",
    icon: Blocks,
    color: "#8b5cf6",
    skills: [
      { name: "Solidity", level: 90, icon: Binary },
      { name: "Web3 Integration", level: 88, icon: Globe },
      { name: "Smart Contracts", level: 92, icon: FileText },
      { name: "DeFi Architecture", level: 85, icon: Component },
    ],
    technologies: [
      "Solidity",
      "Web3.js",
      "Ethers.js",
      "Hardhat",
      "Truffle",
      "IPFS",
      "Ethereum",
      "Polygon",
      "Chainlink",
      "OpenZeppelin",
    ],
  },
  {
    title: "Cloud & DevOps",
    icon: Cloud,
    color: "#f59e0b",
    skills: [
      { name: "AWS/Cloud", level: 87, icon: Cloud },
      { name: "Docker/Containers", level: 90, icon: Box },
      { name: "Kubernetes", level: 78, icon: Component },
      { name: "DevOps Pipeline", level: 85, icon: FileSearch },
    ],
    technologies: [
      "AWS",
      "Google Cloud",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Jenkins",
      "GitHub Actions",
      "Nginx",
      "Linux",
      "Monitoring",
    ],
  },
  {
    title: "Mobile Development",
    icon: Smartphone,
    color: "#ec4899",
    skills: [
      { name: "React Native", level: 80, icon: Smartphone },
      { name: "Flutter", level: 75, icon: Component },
      { name: "iOS/Android", level: 70, icon: Cpu },
    ],
    technologies: [
      "React Native",
      "Flutter",
      "Expo",
      "Swift",
      "Kotlin",
      "Firebase",
      "App Store",
      "Google Play",
      "Push Notifications",
      "Mobile UI/UX",
    ],
  },
  {
    title: "Design & Tools",
    icon: Palette,
    color: "#f97316",
    skills: [
      { name: "UI/UX Design", level: 78, icon: Palette },
      { name: "Figma", level: 82, icon: Component },
      { name: "Git", level: 95, icon: GitBranch },
    ],
    technologies: [
      "Figma",
      "Adobe XD",
      "Git",
      "GitHub",
      "VS Code",
      "Postman",
      "Jira",
      "Slack",
      "Notion",
      "Linear",
    ],
  },
];

// Project categories
export const PROJECT_CATEGORIES = [
  "All",
  "Blockchain",
  "Full-Stack",
  "Mobile",
  "Backend",
] as const;

// Portfolio projects
export const PROJECTS: Project[] = [
  {
    title: "DeFiSwap Protocol",
    description:
      "Enterprise-grade decentralized exchange with advanced AMM algorithms, cross-chain compatibility, and institutional-level security. Processed over $50M in trading volume with 99.9% uptime.",
    category: "Blockchain",
    icon: Blocks,
    color: "#8b5cf6",
    technologies: [
      "Solidity",
      "React",
      "Ethers.js",
      "Node.js",
      "PostgreSQL",
      "Redis",
    ],
    features: [
      "Multi-chain DEX",
      "Advanced AMM",
      "Yield Farming",
      "Governance Token",
      "Flash Loans",
    ],
    github: "https://github.com/davidtaylor/defiswap",
    demo: "https://defiswap-demo.vercel.app",
    image: "/placeholder.svg?height=200&width=400",
    status: "Live in Production",
    metrics: "$50M+ TVL, 10K+ Users",
  },
  {
    title: "TechCorp Analytics Suite",
    description:
      "Real-time business intelligence platform serving Fortune 500 companies. Processes 10M+ events daily with sub-second latency and provides actionable insights through AI-powered analytics.",
    category: "Full-Stack",
    icon: Database,
    color: "#10b981",
    technologies: [
      "React",
      "Node.js",
      "Redis",
      "PostgreSQL",
      "Docker",
      "Kubernetes",
      "Apache Kafka",
    ],
    features: [
      "Real-time Streaming",
      "AI Insights",
      "Custom Dashboards",
      "Multi-tenant Architecture",
      "API Gateway",
    ],
    github: "https://github.com/davidtaylor/analytics-suite",
    demo: "https://analytics-demo.techcorp.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "Enterprise Solution",
    metrics: "10M+ Events/Day, 500+ Clients",
  },
  {
    title: "ConnectPro Mobile Platform",
    description:
      "Professional networking mobile application with advanced matching algorithms, video conferencing, and blockchain-verified credentials. Achieved 100K+ downloads in first 6 months.",
    category: "Mobile",
    icon: Smartphone,
    color: "#ec4899",
    technologies: [
      "React Native",
      "Firebase",
      "Node.js",
      "MongoDB",
      "AWS",
      "WebRTC",
    ],
    features: [
      "AI Matching",
      "Video Calls",
      "Blockchain Credentials",
      "Real-time Chat",
      "Event Management",
    ],
    github: "https://github.com/davidtaylor/connectpro",
    demo: "https://connectpro-app.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "App Store Featured",
    metrics: "100K+ Downloads, 4.8★ Rating",
  },
  {
    title: "ShopScale Microservices Platform",
    description:
      "Cloud-native e-commerce platform handling Black Friday traffic spikes of 1M+ concurrent users. Built with event-driven architecture and auto-scaling capabilities for enterprise retailers.",
    category: "Backend",
    icon: Globe,
    color: "#3b82f6",
    technologies: [
      "Node.js",
      "Docker",
      "Kubernetes",
      "PostgreSQL",
      "Redis",
      "RabbitMQ",
      "Elasticsearch",
    ],
    features: [
      "Event-Driven Architecture",
      "Auto-scaling",
      "Payment Gateway",
      "Inventory Sync",
      "Order Orchestration",
    ],
    github: "https://github.com/davidtaylor/shopscale",
    demo: "https://shopscale-demo.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "Production Ready",
    metrics: "1M+ Concurrent Users, 99.99% Uptime",
  },
  {
    title: "ArtVault NFT Marketplace",
    description:
      "Premium NFT marketplace for digital artists with advanced royalty systems, fractional ownership, and cross-chain compatibility. Facilitated $5M+ in NFT transactions with zero security incidents.",
    category: "Blockchain",
    icon: Blocks,
    color: "#8b5cf6",
    technologies: [
      "Solidity",
      "Next.js",
      "IPFS",
      "Ethers.js",
      "Tailwind",
      "The Graph",
      "Polygon",
    ],
    features: [
      "Cross-chain Trading",
      "Fractional NFTs",
      "Advanced Royalties",
      "Creator Tools",
      "Gasless Transactions",
    ],
    github: "https://github.com/davidtaylor/artvault",
    demo: "https://artvault-nft.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "Live Marketplace",
    metrics: "$5M+ Volume, 2K+ Artists",
  },
  {
    title: "PredictIQ Analytics Platform",
    description:
      "AI-driven predictive analytics SaaS serving 200+ enterprise clients. Delivers 94% accuracy in demand forecasting and reduces operational costs by 30% through intelligent automation.",
    category: "Full-Stack",
    icon: Brain,
    color: "#10b981",
    technologies: [
      "Python",
      "React",
      "TensorFlow",
      "FastAPI",
      "PostgreSQL",
      "Apache Airflow",
      "AWS SageMaker",
    ],
    features: [
      "Predictive Models",
      "Automated ML Pipeline",
      "Real-time Inference",
      "Custom Algorithms",
      "A/B Testing",
    ],
    github: "https://github.com/davidtaylor/predictiq",
    demo: "https://predictiq-demo.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "SaaS Platform",
    metrics: "200+ Clients, 94% Accuracy",
  },
  {
    title: "CryptoTrade Pro Exchange",
    description:
      "Institutional-grade cryptocurrency exchange with sub-millisecond order matching, supporting 100+ trading pairs and handling $10M+ daily volume with bank-level security.",
    category: "Blockchain",
    icon: Blocks,
    color: "#8b5cf6",
    technologies: [
      "Go",
      "React",
      "WebSocket",
      "Redis",
      "PostgreSQL",
      "Kafka",
      "Docker",
    ],
    features: [
      "HFT Order Matching",
      "Margin Trading",
      "API Trading",
      "Cold Storage",
      "KYC/AML Compliance",
    ],
    github: "https://github.com/davidtaylor/cryptotrade-pro",
    demo: "https://cryptotrade-demo.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "Licensed Exchange",
    metrics: "$10M+ Daily Volume, <1ms Latency",
  },
  {
    title: "CloudOps Automation Platform",
    description:
      "Enterprise DevOps platform managing 1000+ cloud resources across AWS, GCP, and Azure. Reduced infrastructure costs by 40% through intelligent resource optimization and automated scaling.",
    category: "Backend",
    icon: Globe,
    color: "#3b82f6",
    technologies: [
      "Go",
      "Terraform",
      "Kubernetes",
      "AWS",
      "GCP",
      "Azure",
      "Prometheus",
      "Grafana",
    ],
    features: [
      "Multi-cloud Orchestration",
      "Cost Optimization",
      "Auto-healing",
      "Security Compliance",
      "Resource Monitoring",
    ],
    github: "https://github.com/davidtaylor/cloudops-platform",
    demo: "https://cloudops-demo.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "Enterprise Tool",
    metrics: "1000+ Resources, 40% Cost Reduction",
  },
  {
    title: "MedConnect Healthcare Platform",
    description:
      "HIPAA-compliant healthcare management system serving 50+ medical practices. Streamlined patient care with integrated EHR, telemedicine, and AI-powered diagnostic assistance.",
    category: "Full-Stack",
    icon: Database,
    color: "#10b981",
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "Socket.io",
      "AWS",
      "WebRTC",
      "TensorFlow",
    ],
    features: [
      "Electronic Health Records",
      "Telemedicine",
      "AI Diagnostics",
      "Appointment System",
      "Prescription Management",
    ],
    github: "https://github.com/davidtaylor/medconnect",
    demo: "https://medconnect-demo.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "HIPAA Certified",
    metrics: "50+ Practices, 10K+ Patients",
  },
  {
    title: "SmartCity IoT Infrastructure",
    description:
      "Scalable IoT data pipeline processing 1M+ sensor readings per minute for smart city initiatives. Enables real-time traffic optimization and environmental monitoring across metropolitan areas.",
    category: "Backend",
    icon: Database,
    color: "#3b82f6",
    technologies: [
      "Python",
      "Apache Kafka",
      "InfluxDB",
      "Docker",
      "Kubernetes",
      "Apache Spark",
      "MQTT",
    ],
    features: [
      "Stream Processing",
      "Edge Analytics",
      "Predictive Maintenance",
      "Real-time Dashboards",
      "Alert Systems",
    ],
    github: "https://github.com/davidtaylor/smartcity-iot",
    demo: "https://smartcity-demo.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "Municipal Deployment",
    metrics: "1M+ Sensors, 5 Cities",
  },
  {
    title: "SecureAudit Smart Contract Scanner",
    description:
      "Automated security analysis platform for smart contracts, detecting 95% of common vulnerabilities. Used by 50+ DeFi protocols to ensure code security before deployment.",
    category: "Blockchain",
    icon: Shield,
    color: "#8b5cf6",
    technologies: [
      "Python",
      "Solidity",
      "React",
      "Node.js",
      "Docker",
      "Machine Learning",
    ],
    features: [
      "Vulnerability Detection",
      "Gas Optimization",
      "Security Reports",
      "CI/CD Integration",
      "Risk Scoring",
    ],
    github: "https://github.com/davidtaylor/secureaudit",
    demo: "https://secureaudit-demo.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "Security Tool",
    metrics: "50+ Protocols, 95% Detection Rate",
  },
  {
    title: "StreamMax Video Platform",
    description:
      "Enterprise video streaming platform supporting 1M+ concurrent viewers with adaptive bitrate streaming, global CDN distribution, and real-time analytics for media companies.",
    category: "Full-Stack",
    icon: Globe,
    color: "#10b981",
    technologies: [
      "React",
      "Node.js",
      "FFmpeg",
      "AWS",
      "CloudFront",
      "WebRTC",
      "HLS",
    ],
    features: [
      "Adaptive Streaming",
      "Global CDN",
      "Live Broadcasting",
      "Analytics Dashboard",
      "Content Protection",
    ],
    github: "https://github.com/davidtaylor/streammax",
    demo: "https://streammax-demo.com",
    image: "/placeholder.svg?height=200&width=400",
    status: "Enterprise Platform",
    metrics: "1M+ Concurrent Users, 99.9% Uptime",
  },
];

// Workflow Steps
export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: 1,
    title: "Discovery & Planning",
    description: "Understanding your vision and technical requirements",
    icon: MessageSquare,
    color: "#3b82f6",
    bgColor: "bg-blue-500/10",
    duration: "1-2 weeks",
    details: [
      "Initial consultation & requirement gathering",
      "Technical architecture planning",
      "Project timeline & milestone definition",
      "Technology stack selection",
    ],
  },
  {
    id: 2,
    title: "Analysis & Design",
    description: "Creating detailed specifications and system design",
    icon: FileSearch,
    color: "#10b981",
    bgColor: "bg-green-500/10",
    duration: "1-2 weeks",
    details: [
      "System architecture design",
      "Database schema planning",
      "API specification documentation",
      "UI/UX wireframes & mockups",
    ],
  },
  {
    id: 3,
    title: "Development & Coding",
    description: "Building your solution with clean, scalable code",
    icon: Code,
    color: "#8b5cf6",
    bgColor: "bg-purple-500/10",
    duration: "4-12 weeks",
    details: [
      "Agile development methodology",
      "Clean code & best practices",
      "Regular progress updates",
      "Version control & documentation",
    ],
  },
  {
    id: 4,
    title: "Testing & Quality Assurance",
    description: "Ensuring reliability and performance standards",
    icon: TestTube,
    color: "#f59e0b",
    bgColor: "bg-yellow-500/10",
    duration: "1-2 weeks",
    details: [
      "Unit & integration testing",
      "Performance optimization",
      "Security vulnerability testing",
      "Cross-platform compatibility",
    ],
  },
  {
    id: 5,
    title: "Deployment & Launch",
    description: "Going live with proper monitoring and support",
    icon: Rocket,
    color: "#ef4444",
    bgColor: "bg-red-500/10",
    duration: "1 week",
    details: [
      "Production environment setup",
      "CI/CD pipeline configuration",
      "Monitoring & logging setup",
      "Go-live support",
    ],
  },
  {
    id: 6,
    title: "Support & Maintenance",
    description: "Ongoing support and feature enhancements",
    icon: Users,
    color: "#06b6d4",
    bgColor: "bg-cyan-500/10",
    duration: "Ongoing",
    details: [
      "24/7 monitoring & support",
      "Regular updates & patches",
      "Performance optimization",
      "Feature enhancements",
    ],
  },
];
